Post: Custom Common Libraries For Integration Services
Backbase/backbase.github.io pull request #115
Opened 2024-04-25 07:15 UTC by furkan-bb

### What is this article about?
Custom Common Libraries For Integration Services

### Checklist:

- [x] I am added to the list of authors correctly.
- [x] All images used in the post is in the correct folder (`assets/images/post/`).
- [x] My article has been reviewed internally before opening this Pull Request.
- [x] I have not modified someone else's previously published articles.
- [x] I double checked my changes locally at http://127.0.0.1:4000/ after running `bundle install && bundle exec jekyll serve`.
- [x] My changes generate no new errors

2024-05-06 08:04 UTC, tarun-bb requested changes

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +In the ever-expanding landscape of software development, effective communication between different services and systems is crucial. Integrating external APIs into your projects often presents challen
Please include code duplication and consistent across multiple service aspect in the intro too

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +@Qualifier("ssbRestTemplate")
remove ssb

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +1. **Consistency**: By encapsulating communication logic within a reusable library, you ensure consistency across your projects. This consistency simplifies maintenance and reduces the likelihood of
replace `communication` with `common`

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +## **Introducing Communication Libraries**
Let's stick to only introduction

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +## **Introducing CS Communication Library**
Please review CS keyword and make it generic

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +Avoid commonizing business logic implementation and UI/UX design components when the requirements are highly specialized or unique to specific domains or platforms. Attempting to generalize intricate
Can we have bullet points on when not use.  Please review UI/UX part, post is for BE dont know why we are mentioning the it.

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +## **Introducing Communication Libraries**
I feel like there is confusion b/w commons vs communication.

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +Discover the best practices and considerations for commonizing aspects of software development, including custom libraries, business logic and error handling. Learn when commonization enhances effici
remove error handling

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +tags: custom, communication, integration, services, commonize, backend, logging, error, handling, libraries, library
same from here

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +## **Introducing Common Libraries**
Rename it to just introduction

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +Common libraries are like toolboxes for developers, helping simplify tasks, reuse code, decrease code duplication and keep projects organized. They're essential for making coding easier and projects
mention about consistency as well

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +In this post, we go through the importance of custom common libraries in backend development, exploring their benefits, structures, and considerations. We'll discuss common library structures, explor
Can you please rewrite it to mention what exact this post is explaining. For e.g. I dont see any heading with name importance, benefits etc

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +1. **Avoid Code Duplication**: By centralizing common functionalities in a custom library, developers can avoid duplicating code across projects.
Can we specify an example for each of this point

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +## **Introducing CS Common Library**
I think we discussed not to have CS Common Library in the post since that's an example from a project and it is not the library that everyone can use in their project as it is.

But you can use it to enrich your post with what can be put inside the  common lib, like we can have multiple types of common lib (communication, logging, token etc) and what each of these lib can contain

2024-05-06 08:04 UTC, tarun-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +- **RestTemplate Creation**: Simplified creation of RestTemplate instances using Apache HTTP Client.
this can be put as an example for the list of items can be put under custom communication lib

2024-05-13 06:45 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +In the ever-expanding landscape of software development, effective communication between different services and systems is crucial. Integrating external APIs into your projects often presents challen
updated

2024-05-13 06:45 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +@Qualifier("ssbRestTemplate")
updated

2024-05-13 06:45 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +1. **Consistency**: By encapsulating communication logic within a reusable library, you ensure consistency across your projects. This consistency simplifies maintenance and reduces the likelihood of
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +## **Introducing Communication Libraries**
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +## **Introducing CS Communication Library**
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +Avoid commonizing business logic implementation and UI/UX design components when the requirements are highly specialized or unique to specific domains or platforms. Attempting to generalize intricate
updated already

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-integration-services/post.md
> +## **Introducing Communication Libraries**
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +Discover the best practices and considerations for commonizing aspects of software development, including custom libraries, business logic and error handling. Learn when commonization enhances effici
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +tags: custom, communication, integration, services, commonize, backend, logging, error, handling, libraries, library
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +## **Introducing Common Libraries**
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +Common libraries are like toolboxes for developers, helping simplify tasks, reuse code, decrease code duplication and keep projects organized. They're essential for making coding easier and projects
updated

2024-05-13 06:46 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +In this post, we go through the importance of custom common libraries in backend development, exploring their benefits, structures, and considerations. We'll discuss common library structures, explor
updated already

2024-05-13 06:47 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +1. **Avoid Code Duplication**: By centralizing common functionalities in a custom library, developers can avoid duplicating code across projects.
detailed them in advantages section

2024-05-13 06:48 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +## **Introducing CS Common Library**
updated and put details about them in **Areas of Common Libraries**

2024-05-13 06:49 UTC, furkan-bb commented on content/posts/unpublished/custom-common-libraries-for-backend-services/post.md
> +- **RestTemplate Creation**: Simplified creation of RestTemplate instances using Apache HTTP Client.
updated

2024-05-14 16:26 UTC, nafelaraz approved these changes

2024-05-14 19:30 UTC, uesleilima approved these changes
Great work guys

2024-05-14 21:22 UTC, tarun-bb approved these changes

2024-05-14 21:23 UTC, merged