Post: Resilient Microservices
Backbase/backbase.github.io pull request #132
Opened 2024-05-24 14:16 UTC by Sebbackbase

### What is this article about?
# Resilient Microservices

How can we make our microservice more resilient?

2024-05-28 15:43 UTC, tarun-bb approved these changes

2024-06-28 14:29 UTC, uesleilima requested changes

2024-06-28 14:29 UTC, uesleilima commented on content/posts/unpublished/resilient-microservices/post.md
> +## Applicaion live properties:
```suggestion
## Application live properties:
```

2024-06-28 14:29 UTC, uesleilima commented on content/posts/unpublished/resilient-microservices/post.md
> +### **Understanding Microservices Resillence and Reiliency pattern**
```suggestion
### **Understanding Microservices Resilience and Resiliency pattern**
```

2024-06-28 14:31 UTC, uesleilima approved these changes
]

2024-06-28 15:01 UTC, merged