Script to resize the images
Backbase/backbase.github.io pull request #98
Opened 2024-02-22 10:51 UTC by a1exymoroz

### What is this PR about?
- script to resize post images

2024-02-22 14:05 UTC, robinsonzimmermann requested changes
Please add the directory with the processed images to .gitignore

2024-02-22 14:05 UTC, robinsonzimmermann commented on tools/process-post-images/index.js
> +updateSizeImage(sourceDir);
Can't we reuse the existing script passing some parameters?

2024-02-22 15:50 UTC, a1exymoroz commented on tools/process-post-images/index.js
> +updateSizeImage(sourceDir);
No. Because we need to recursively check all folders.

2024-02-29 10:56 UTC, a1exymoroz commented on tools/process-post-images/index.js
> +updateSizeImage(sourceDir);
Done

2024-02-29 11:28 UTC, robinsonzimmermann commented
The images of related posts get broken when you navigate from one post to another. Can you take a look at it, please?

Other than that, looks good!

<img width="1018" alt="image" src="https://github.com/Backbase/backbase.github.io/assets/16561945/89bee9a0-4ce9-46a1-9de6-7db8f2de4123">

2024-02-29 14:03 UTC, robinsonzimmermann approved these changes

2024-02-29 15:34 UTC, merged